### PR TITLE
Update Pyroma to 4.0 & recipe to modern standards, and expand tests

### PR DESCRIPTION
**Pull request by CAM-Gerlach**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] ~Bumped the build number (if the version is unchanged)~
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes: #10
Closes: #11
Closes: #12
Closes: #13

**Note**: I'm initially updating to Pyroma 4.0 rather than 4.1, as the latter requires `trove-classifiers` which is not yet packaged with Conda, and that in turn requires the also missing `calver` at build time, though PEP 517 build isolation means we might be able to get away with not packaging it). I plan to submit those feedstocks once this PR is ready; by the point, this PR is merged, we might be able to jump right to Pyroma 4.2, as 4.1 adds some more requirements and complexity that I plan to change/relax in 4.2.

This PR:

* Updates the recipe to follow modern standards and best prctices, and avoid deprecated/legacy constructs
    * `fn` is no longer needed unless using a non-standard filename
    * Use current standard `pip` invocation
    * Use variables for entrypoint and import name rather than hardcoding
    * Remove `preserve_egg_dir` option, which is no longer needed with modern CF and Pyroma
already; I'll verify after I get everything passing cleanly here first)
* Update to Pyroma 4.0
    * Update version and hash
    * Add Python lower bounds (per noarch requirements)
    * Update runtime dependencies
    * Update website (see regebro/pyroma#63 )
* Greatly improve testing
    * Add standard `pip check`
    * Add actual unit test invocation and required deps/source files
* Rerender feedstock to up to date infra

### CODE REVIEW

**Comment by CAM-Gerlach** [comment]
@conda-forge-admin, please rerender

**Comment by CAM-Gerlach** [comment]
@conda-forge-admin, please rerender

**Comment by CAM-Gerlach** [comment]
Hey @jakirkham you're welcome to review this if you like. If I don't hear otherwise from you'll, I can go ahead and merge this in a few days time. Thanks!

**Comment by CAM-Gerlach** [comment]
@conda-forge-admin, please rerender

**Comment by CAM-Gerlach** [comment]
Going ahead and merging this :+1:

**Comment by jakirkham** [comment]
Thank you! 🙏

**Pull request merged**
